CREATE DATABASE ssdb;

CREATE TABLE USERS(
	UserCode VARCHAR(13) PRIMARY KEY NOT NULL,
    Rut VARCHAR(15) NOT NULL,
    Username VARCHAR(15) NOT NULL,
    Firstname VARCHAR(25) NOT NULL,
    Lastname VARCHAR(25) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Role VARCHAR(50) NOT NULL,
    Passwd VARCHAR(64) NOT NULL,
    Type INTEGER NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP,
    LastLogin TIMESTAMP NOT NULL,
    ParentOrg VARCHAR(13) DEFAULT 'NAN'
);