
-- THIS SCRIPT WAS GENERATED AUTMATICALLY FROM NODE JS (By KBeDeveloper)


DROP DATABASE IF EXISTS ssdb;
CREATE DATABASE IF NOT EXISTS ssdb CHARACTER SET utf8 COLLATE utf8_general_ci;
USE ssdb;

CREATE TABLE IF NOT EXISTS USERS (

    `Code` VARCHAR(13) PRIMARY KEY,
    `RUT` VARCHAR(12) NOT NULL UNIQUE,
    `Firstname` VARCHAR(30),  -- UNICODE, UTF-8, NO_SPECIAL_CHARS
    `Lastname` VARCHAR(30),  -- UNICODE, UTF-8, NO_SPECIAL_CHARS
    `Phone` INTEGER(9) NOT NULL UNIQUE,
    `Street` VARCHAR(50) NOT NULL,
    `HouseNumber` VARCHAR(8) NOT NULL,
    `City` VARCHAR(25) NOT NULL,
    `State` VARCHAR(30) NOT NULL,
    `Country` VARCHAR(30) NOT NULL,
    `Type` INTEGER(1) NOT NULL,
    `Email` VARCHAR(40) NOT NULL UNIQUE,
    `Pass` VARCHAR(64) NOT NULL,
    `Token` VARCHAR(32) DEFAULT NULL,  -- UTF-8
    `TokenTime` TIMESTAMP DEFAULT NULL,
    `CreatedAt` TIMESTAMP DEFAULT NOW(),
    `UpdatedAt` TIMESTAMP DEFAULT NULL,
    `LoggedAt` TIMESTAMP DEFAULT NULL,
    `ParentOrg` VARCHAR(13) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS EVENTS (

    `EventId` VARCHAR(32) PRIMARY KEY,
    `SupervisorCorp` VARCHAR(50) NOT NULL,
    `Type` INTEGER(1) NOT NULL,
    `CreatedAt` TIMESTAMP NOT NULL,
    `ClosedAt` TIMESTAMP DEFAULT NULL,
    `SubmittedAt` TIMESTAMP DEFAULT NOW(),
    `UserCode` VARCHAR(13) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS COMMENTS (

    `CommentId` VARCHAR(32) PRIMARY KEY,
    `Content` TEXT,  -- UNICODE, UTF-8
    `Type` VARCHAR(32),  -- UNICODE, UTF-8
    `EventId` VARCHAR(32) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TOOLS (

    `ToolId` VARCHAR(32) PRIMARY KEY,
    `Name` VARCHAR(50) NOT NULL,
    `Status` INTEGER(1) NOT NULL,
    `EventId` VARCHAR(32) NOT NULL
) ENGINE=InnoDB;


ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENTS_UserCode FOREIGN KEY (UserCode) REFERENCES USERS(Code);
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_EventId FOREIGN KEY (EventId) REFERENCES EVENTS(EventId);
ALTER TABLE TOOLS ADD CONSTRAINT FK_TOOLS_EventId FOREIGN KEY (EventId) REFERENCES EVENTS(EventId);