/* DEFINE DB COLLATION AND CHARSET */

CREATE DATABASE ssdb CHARACTER SET utf8 COLLATE utf8_general_ci;

USE ssdb;

/* DROP TABLES */

DROP TABLE ATTENDACES;
DROP TABLE COMMENTS;
DROP TABLE FILES;
DROP TABLE EVENTS;
DROP TABLE USERS;

/* CREATE TABLES */

CREATE TABLE USERS(
	Code VARCHAR(13) PRIMARY KEY NOT NULL,
    Rut VARCHAR(15) NOT NULL,
    Username VARCHAR(15) DEFAULT NULL,
    Firstname VARCHAR(25) NOT NULL,
    Lastname VARCHAR(25) NOT NULL,
    Phone INTEGER NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Role VARCHAR(50) NOT NULL,
    Pass VARCHAR(64) NOT NULL,
    Token VARCHAR(64) NOT NULL UNIQUE,
    TokenTime TIMESTAMP NOT NULL,
    Type INTEGER NOT NULL,
    CreatedAt TIMESTAMP DEFAULT NOW() NOT NULL,
    UpdatedAt TIMESTAMP,
    LoggedAt TIMESTAMP NOT NULL,
    ParentOrg VARCHAR(13) DEFAULT 'NAN' NOT NULL
) ENGINE=InnoDB;

CREATE TABLE EVENTS(
    EventId VARCHAR(32) PRIMARY KEY NOT NULL,
    Type INTEGER NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    ClosedAt TIMESTAMP NOT NULL,
    SubmittedAt TIMESTAMP DEFAULT NOW() NOT NULL,
    UserCode VARCHAR(13) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE FILES(
    FileId VARCHAR(32) PRIMARY KEY NOT NULL,
    Name VARCHAR(40) NOT NULL UNIQUE,
    UploadedAt TIMESTAMP DEFAULT NOW(),
    Digest MEDIUMTEXT NOT NULL,
    Type INTEGER NOT NULL
    EventId VARCHAR(32) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE COMMENTS(
    CommentId VARCHAR(32) PRIMARY KEY NOT NULL,
    Content TEXT NOT NULL,
    Type VARCHAR(32) NOT NULL,
    EventId VARCHAR(32) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE ATTENDACES(
    AtteId VARCHAR(32) PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT NOW() NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL
)ENGINE=InnoDB;

/* ALTER TABLES */

ALTER TABLE EVENTS ADD CONSTRAINT FK_UserCode_EVENT FOREIGN KEY (UserCode) REFERENCES USERS(Code);

ALTER TABLE FILES ADD CONSTRAINT FK_EventId_FILE FOREIGN KEY (EventId) REFERENCES EVENTS(EventId);

ALTER TABLE COMMENTS ADD CONSTRAINT FK_EventId_COMMENT FOREIGN KEY (EventId) REFERENCES EVENTS(EventId);
