/*
 * THIS SCRIPT WAS GENERATED AUTMATICALLY FROM NODE JS (By KBeDeveloper)
 */

IF EXISTS DROP DATABASE ssdb;
IF NOT EXISTS CREATE DATABASE ssdb CHARACTER SET utf8 COLLATE utf8_general_ci;
USE ssdb;

IF NOT EXISTS CREATE TABLE USERS (
    `Code` VARCHAR(13) PRIMARY KEY,
    `RUT` VARCHAR(12) NOT NULL UNIQUE,
    `Firstname` VARCHAR(30),  -- UNICODE, UTF-8, NO_SPECIAL_CHARS
    `Lastname` VARCHAR(30),  -- UNICODE, UTF-8, NO_SPECIAL_CHARS
    `Phone` INTEGER(9) NOT NULL UNIQUE,
    `Street` VARCHAR(50) NOT NULL,
    `HouseNumber` VARCHAR(8) NOT NULL,
    `City` VARCHAR(25) NOT NULL,
    `State` VARCHAR(30) NOT NULL,
    `Country` VARCHAR(30) NOT NULL,
    `Type` INTEGER(1) NOT NULL,
    `Email` VARCHAR(40) NOT NULL UNIQUE,
    `Pass` VARCHAR(64) NOT NULL,
    `Token` VARCHAR(32) DEFAULT NULL,  -- UTF-8
    `TokenTime` TIMESTAMP DEFAULT NULL,
    `CreatedAt` TIMESTAMP DEFAULT NOW(),
    `UpdatedAt` TIMESTAMP DEFAULT NULL,
    `LoggedAt` TIMESTAMP DEFAULT NULL,
    `ParentOrg` VARCHAR(13) DEFAULT NULL,
) ENGINE=InnoDB;

IF NOT EXISTS CREATE TABLE EVENTS (
    `EventId` VARCHAR(32) PRIMARY KEY,
    `SupervisorCorp` VARCHAR(50) NOT NULL,
    `Type` INTEGER(1) NOT NULL,
    `CreatedAt` TIMESTAMP NOT NULL,
    `ClosedAt` TIMESTAMP DEFAULT NULL,
    `SubmittedAt` TIMESTAMP DEFAULT NOW(),
    `UserCode` VARCHAR(13) NOT NULL,
) ENGINE=InnoDB;

IF NOT EXISTS CREATE TABLE COMMENTS (
    `CommentId` VARCHAR(32) PRIMARY KEY,
    `Content` TEXT,  -- UNICODE, UTF-8
    `Type` VARCHAR(32),  -- UNICODE, UTF-8
    `EventId` VARCHAR(32) NOT NULL,
) ENGINE=InnoDB;

IF NOT EXISTS CREATE TABLE TOOLS (
    `ToolId` VARCHAR(32) PRIMARY KEY,
    `Name` VARCHAR(50) NOT NULL,
    `Status` INTEGER(1) NOT NULL,
    `EventId` VARCHAR(32) NOT NULL,
) ENGINE=InnoDB;

